#!/bin/sh

# https://github.com/jason-thinks/quick-build/qj

#    DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#                    Version 2, December 2004
#
# Copyright (C) 2004 Sam Hocevar <sam@hocevar.net>
#
# Everyone is permitted to copy and distribute verbatim or modified
# copies of this license document, and changing it is allowed as long
# as the name is changed.
#
#            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION
#
#  0. You just DO WHAT THE FUCK YOU WANT TO.

name=$(basename "$PWD")

cmd="$1"
if [ -z "$cmd" ]; then
    cmd='run'
fi

log() {
    [ -z "$LOG" ] || echo "LOG: $1" >&2
}

build() {
    log 'build'

    [ -d out ] || mkdir out

    time -f 'compile: %e seconds' javac -Werror -Xlint -profile compact1 -proc:none -encoding utf-8 -d out -cp out -sourcepath src src/main.java
}

clean() {
    log 'clean'

    rm -rf out
}

run() {
    log 'run'

    clean

    main_class="$1"
    if [ -z "$main_class" ]; then
        main_class='main'
    fi

    build && java -cp out "$main_class"
}

if [ "$cmd" = 'build' ]; then
    build
elif [ "$cmd" = 'clean' ]; then
    clean
elif [ "$cmd" = 'run' ]; then
    run "$2"
fi

